export * from "./basics-section";
export * from "./work-section";
export * from "./education-section";
export * from "./skills-section";
export * from "./projects-section";
export * from "./awards-section";
export * from "./certificates-section";
export * from "./publications-section";
export * from "./volunteer-section";
